project_name: dummy_app_{env}

environments:
  staging:
    machine:
      host:    'tcp://123.123.123:1231'
      ca_cert: 'certs/staging/ca.pem'
      cert:    'certs/staging/cert.pem'
      key:     'certs/staging/key.pem'

  testing:
    project_name: dummy_app_staging
    config_files:
      - config/production.yml
      - config/testing.yml
