stages:
  - test
  - release

before_script:
  - bundle install

run_tests:
  stage: test
  script:
    - bundle exec rspec

run_linter:
  stage: test
  script:
    - bundle exec rubocop -D

release_to_rubygems:
  stage: release
  only:
    - /^v\d+\.\d+\.\d+$/
  script:
    - mkdir -p /.gem
    - echo -e "---\n:rubygems_api_key: d58a6215a60447af9e883a5ebbb6e7eb" > /.gem/credentials
    - rake release
