stages:
  - test
  - release

before_script:
  - bundle install

run_tests:
  stage: test
  script:
    - bundle exec rspec

run_linter:
  stage: test
  script:
    - bundle exec rubocop -D

relase_to_rubygems:
  stage: release
  only:
    - /^v\d+\.\d+\.\d+$/
  script:
    - rake release
